#branch_pipeline
name: Revisando Infra
on:
  push:
    branches:
      - main
jobs:
  Revisando_Infra:
    runs-on: ubuntu-latest
    steps:
    # - name: Ingress to the directory
    #   run: |
    #     cd environments/
    #     cd dev/
    # - name: Ingress to the directory
    #   run: cd dev/
    - name: Checkout Repo
      uses: actions/checkout@v1
      working-directory: ./environments/dev/
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      working-directory: ./environments/dev/
    - name: Terraform Init
      working-directory: ./environments/dev/
      run: terraform init
      # env:
      #   AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
      #   AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color
    # - name: Configure AWS credentials
    #   uses: aws-actions/configure-aws-credentials@v1
    #   with:
    #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #     aws-region: us-east-1
    - name: Terraform Plan
      id: plan
      run: terraform plan -no-color
      continue-on-error: true