#branch_pipeline
name: Revisando Infra
on:
  push:
    branches:
      - main
jobs:
  Revisando_Infra:
#    runs-on: ubuntu-latest
    runs-on: self-hosted
    # defaults:
    #   run:
    #     working-directory: environments/dev/
    steps:
    # - name: Ingress to the directory
    #   run: |
    #     cd environments/
    #     cd dev/
    # - name: Ingress to the directory
    #   run: cd dev/
    - name: Checkout Repo
      uses: actions/checkout@v1
#      working-directory: ./environments/dev/
#    - name: Setup Terraform
#      uses: hashicorp/setup-terraform@v1
    - name: Setup Terraform
      uses: little-core-labs/install-terraform@v2.0.0
      with:
          version: 0.13.4
#      working-directory: ./environments/dev/
    # - name: Display the path
    #   run: echo $PATH
    #   shell: bash
    - name: Terraform Init
#      working-directory: ./environments/dev/
      run: terraform init
      working-directory: environments/dev/
      env:
        AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color 
      working-directory: environments/dev/
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    # - name: Configure AWS credentials
    #   uses: aws-actions/configure-aws-credentials@v1
    #   with:
    #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #     aws-region: us-east-1
    # - name: Terraform Lock false
    #   id: force-unlock
    #   run: terraform force-unlock a4ab11e4-3ec0-d646-6253-278cbf20fc80
    #   working-directory: environments/dev/
    #   continue-on-error: false
    - name: Terraform Plan 
      id: plan
      run: terraform plan -no-color -lock=false -var-file=dev.tfvars
      working-directory: environments/dev/
      continue-on-error: true
      #